#!/bin/bash
#PBS -q braintv
#PBS -N ophys_deepint
#PBS -l mem=250g,walltime=10:00:00
#PBS -l nodes=1:ppn=88:gpus=4
#PBS -j oe
#PBS -o /allen/aibs/informatics/danielk/deepinterpolation/logs

image=docker://alleninstitutepika/deepinterpolation:develop
TMPDIR=/scratch/capacity/${PBS_JOBID}
model_file=/allen/programs/braintv/workgroups/ophysdev/OPhysCore/Deep2p/unet_single_1024_mean_absolute_error_Ai93_2019_09_11_23_32/2019_09_11_23_32_unet_single_1024_mean_absolute_error_Ai93-0450.h5
movie_path=/allen/programs/braintv/workgroups/neuralcoding/2p_data/single_plane/ground_truth/20191215_raw_noisy_time_first.h5

SINGULARITY_TMPDIR=${TMPDIR} singularity run \
    --bind /allen:/allen,/scratch/capacity/${PBS_JOBID}:/tmp \
    --nv \
    ${image} python -m \
        deepinterpolation.cli.transfer_trainer \
        --train_path ${movie_path} \
        --training_params.model_path ${model_file} \
        --output_dir /allen/aibs/informatics/danielk/deepinterpolation/output4 \
	--set_defaults ophys \
	--generator_params.total_samples 10000 \
	--generator_test_params.total_samples 1000 \
        --batch_size 5 \
	--training_params.nb_gpus 4 \
	--training_params.nb_times_through_data 1
